### ISSUE TITLE
[Performance Improvement] Sprite Batching/Instancing

### ISSUE THREAD

**Issue by Bombfuse** [Bombfuse/emerald#10]
This should greatly improve performance, essential before 1.0 release.

Miniquad example [here](https://github.com/not-fl3/miniquad/blob/master/examples/instancing.rs)

**Comment by nezvers** [comment]
Here's a beautiful explanation in 4 videos by [Cherno](https://youtu.be/Th4huqR77rI?list=PLlrATfBNZ98foTJPJ_Ev03o2oq3-GGOS2).
