### ISSUE TITLE
platform icons for dark theme

### ISSUE THREAD

**Issue by PSteinhaus** [Bombfuse/emerald#103]
This is a very minor thing, but as a dark theme user, looking at your repo I noticed that the icons for the supported platforms are nearly invisible for me (and other dark theme users).

Since I was already fiddling with them for something else I took the liberty to add a white background, if you're interested: [icons.zip](https://github.com/Bombfuse/emerald/files/7232252/icons.zip)

**Comment by Bombfuse** [comment]
Yah I've noticed it as well but never got around to fixing it 😅

Thanks so much for doing this, I'll update it with these new icons when I get some time!

**Comment by PSteinhaus** [comment]
I just quickly made it into a PR ;)
#104

**Comment by PSteinhaus** [comment]
Btw.: while your main logo is not completely invisible when using dark themes you might still consider giving it a white outline (or something similiar, i.e. white background, white radial gradient, etc.) as well, to improve visibility ;)
