### ISSUE TITLE
Some questions regarding this project

### ISSUE THREAD

**Issue by Raj2032** [Bombfuse/emerald#151]
Hi, I have some questions regarding this project:
1. Does it use wgpu by any chance? If not would it be implemented in the near future?
2. Would it ever support 3D graphics as well?
3. Is there [egui](https://github.com/emilk/egui) integration?
4. Is there a community for `emerald` such as Discord or something?
5. Does it lock you into a framework like [Bevy](https://bevyengine.org/) does or can you code things freely, like in [Macroquad](https://github.com/not-fl3/macroquad)?
6. How does the performance compare with other game engines, is it supposed to be high performance?
7. Does it use [Rapier[(https://rapier.rs/) physics engine? If not what physics engine does it use then?
8. Just curious how come you chose hecs over all the other ecs other such as `legion`?

**Comment by Raj2032** [comment]
Hi @Bombfuse Thanks for your response.

> There is a discord, we're somewhat active in there so feel free to join and discuss :D https://discord.gg/CMUEYgBf2b

Thanks for the link mate :)

For the rest of the questions I will respond on Discord :)

**Comment by Bombfuse** [comment]
Sounds like a plan, thanks for joining!
