### ISSUE TITLE
Load .aseprite files directly

### ISSUE THREAD

**Issue by Bombfuse** [Bombfuse/emerald#40]
[Aseprite file specs](https://github.com/aseprite/aseprite/blob/master/docs/ase-file-specs.md)

Requires parsing out the texture data, and then parsing out the animation data

**Comment by louisgjohnson** [comment]
Happy to help with this, Are you open to using a crate like: https://github.com/alpine-alpaca/asefile or would you like it built directly into the repo?

**Comment by louisgjohnson** [comment]
Never mind, looks like you're already loading in aseprite files?

**Comment by Bombfuse** [comment]
I would love some help with this! Ideally it would be built directly into the engine, I try to keep the dependencies as small as possible.

Currently we load in the sprite.png, and the animations.json files to build an "Aseprite". Ideally, we would just pass the ".aseprite" file to the engine and it would extract the texture and animation data out of it.

Example

Currently:
`let my_aseprite = emd.loader().aseprite_with_animations("path/to/sprite.png", "path/to/animations.json").unwrap();`

Proposed:
`let my_aseprite = emd.loader().aseprite("path/to/my.aseprite").unwrap()`

Note, this shouldn't replace the old function, this is just a new function that improves the user experience by not forcing them to export their aseprite files, at the cost of parsing during runtime.

**Comment by louisgjohnson** [comment]
I'll look into and see what I can do!

**Comment by sapir** [comment]
@louisgjohnson I opened a pr implementing this, apologies if you were still working on this
